# Generated by Django 5.1.6 on 2025-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_service', '0003_collection_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
